---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ouyang.
--- DateTime: 2018/4/2 下午2:56
---

-- 简单模式（simple model）拥有一个当前输入文件和一个当前输出文件，并且提供针对这些文件相关的操作。
-- 完全模式（complete model） 使用外部的文件句柄来实现。它以一种面对对象的形式，将所有的文件操作定义为文件句柄的方法
--file = io.open("type.lua", "r")
--io.input(file)
--print(io.read())
--print(io.read())
-- -- print(io.read("*|"))
--print(io.type(file))
--io.close(file)

--file = io.open("type.lua", "a")
--io.output(file)
--io.write("-- type.lua end")
--io.close(file)

--file = io.open("type.lua", "r")
--print(file:read())
--file:close()
--
--file = io.open("type.lua", "a")
--file:write("--test")
--file:close()

file = io.open("type.lua", "r")
print(file:read())
print(file:seek())
print(file:seek("set"))
print(file:seek("end"))
print(file:seek("end", -10))
file:close()

for line in io.lines("type.lua") do
    print(line)
end

file = io.open("type.lua", "r")
file:seek("end", -26)
print(file:read("*a"))
file:close()