---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ouyang.
--- DateTime: 2018/4/3 下午7:14
---
mytable = {"apple", "orange", "banana"}
print(collectgarbage("count"))
mytable = nil
print(collectgarbage("count"))
print(collectgarbage("collect"))
print(collectgarbage("count"))