---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ouyang.
--- DateTime: 2018/4/3 下午10:52
---
luasql = require("luasql.mysql")
-- 创建环境对象
env = luasql.mysql()
-- 连接数据库
conn = env:connect("test", "root", "root", "localhost", 3306)

--设置数据库的编码格式
--conn:execute"SET NAMES UTF8"

--执行数据库操作
cur = conn:execute("select * from example")

total_row = {}
row = cur:fetch(total_row, "a")

while row do
    var = string.format("%d %s", row.id, row.name)
    print(var)
    row = cur:fetch(total_row, "a")
end

for k, v in pairs(total_row) do
    print(k, v)
end